json.message "hello"
json.dogs "Heather has 2 dogs."
json.early_bird "Tracy"
json.doggo "Thor"
json.tiggers "a wonderful thing"
json.artist "kesha is kween!"
json.best_artist "Ke$ha"
json.merger "conflict"
json.josh "s"
# Heather L
json.message_hl "this is my message"